apiVersion: v1
kind: Service
metadata:
  name: pod-prediction-service
  labels:
    app: pod-prediction
spec:
  selector:
    app: pod-prediction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
